# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=30)),
                ('air_date', models.DateField()),
                ('air_time', models.TimeField()),
            ],
        ),
    ]
