# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='air_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='air_time',
            field=models.TimeField(blank=True),
        ),
    ]
